export const teachersRow =[
    {
        id:1,
        name:"Funmi David",
        gender:"Female",
        email:"funmi@gmail.com",
        phoneNumber:"+2349025766940",
        class:"SS1",
    },
    {
        id:1,
        name:"Funmi David",
        gender:"Female",
        email:"funmi@gmail.com",
        phoneNumber:"+2349025766940",
        class:"SS1",
    },
    {
        id:2,
        name:"Adam Emmanuel",
        gender:"Male",
        email:"adam@gmail.com",
        phoneNumber:"+2349025766940",
        class:"SS3",
    },
    {
        id:3,
        name:"Stephen David",
        gender:"Male",
        email:"stephen@gmail.com",
        phoneNumber:"+2349025766940",
        class:"JS2",
    },
    {
        id:4,
        name:"Temi Adejobi",
        gender:"Female",
        email:"temi@gmail.com",
        phoneNumber:"+2349025766940",
        class:"SS2",
    },
]